### PR TITLE
Streamlined the overall style of the site

### PR DESCRIPTION
**Pull request by dherman**
Streamlined the style of the site header, footer, and navbar, as well as the home page.

Highlights:

- Features some fun neon colors on the front page.
- Rounded, softer rectanges.
- Eliminate code samples on home page and focus on high-level pitch.
- More prominent hero unit.
- Comfortaa font for a fun, retro feel.
- Less blue in the dark background colors.
- Minor tweaks to the information architecture of the docs, but more work is needed.
- Smaller number of navbar items, consolidated into dropdown menus.

Screenshot:

image

### CODE REVIEW

**Comment by amilajack** [comment]
I'd love to revamp [my initial design](https://www.figma.com/file/BcNINOPG3TPxJkBG7vpDbXTn/Neon) with some of the ideas offered from this PR!

**Comment by dherman** [comment]
@amilajack I've updated the PR based on the [design we collaborated on](https://www.figma.com/file/AHM9ZSowavRtfl8E21ZHQc/Home-Page?node-id=33%3A3). I'm a little sad to have dropped the more eclectic colors of my first iteration, but I still think this is a nice step forward for the current site. See what you think!

**Review by amilajack — CHANGES_REQUESTED** [review]
I think the background of the demo should match the secondary background color. It seems to stand out too much. I'm also wondering if we should still even show the demo at all.

Screen Shot 2020-09-10 at 10 23 37 AM

All the backgrounds of the logos have to be updated so that the site is consistent. It seems like the logo still needs the background to be updated:

Screen Shot 2020-09-10 at 10 26 29 AM

**Comment by dherman** [comment]
> I think the background of the demo should match the secondary background color. It seems to stand out too much.

Yeah, I wrestled with this. The background of the features list / footer was too strong to see the foreground text -- there wasn't enough contrast. I can play with either making the features list and footer background to be darker (which would help improve their contrast, too), or making the foreground text colors brighter.

> I'm also wondering if we should still even show the demo at all.

Interesting, why's that?

**Comment by dherman** [comment]
> All the backgrounds of the logos have to be updated so that the site is consistent. It seems like the logo still needs the background to be updated:

Good catch, will fix!

**Comment by dherman** [comment]
@amiljack I landed on `#001624` as a really nice middle ground between the `#001018` and `#002030`. It's darker and slightly less green and more blue, which ended up with several nice benefits:

- Gives us a little more of the blue feel you were going for in your mockups (while still having a touch of green to take some of the edge off)
- Darker so it improves contrast for text in both the feature descriptions and the demo video
- Consistent background color for the feature list, demo video, and footer, as you suggest

I also brightened the text colors in the demo video to improve contrast and readability. It also makes the foreground text colors consistent between the demo video and the feature descriptions.

Definitely interested to hear your thinking about the demo. I certainly think it can be improved as we move towards `npm init` and `cargo build` or `npm i` and away from `neon new` and `neon build`, but for the time being it still gives people an immediate feel for how easy it is to get up and running. And it adds some visual rhythm to the site, which I fear would get too empty without it.

**Review by amilajack — CHANGES_REQUESTED** [review]
I think renaming the header to `About` is somewhat confusing. The docs in that section are intended to be read by people who want to get started with the project. 

Screen Shot 2020-09-10 at 4 52 23 PM

In my opinion, "Getting started" or "Introduction" more accurately describe that section. I've also never seen a section of introductory docs being called About. I usually see about pages labeled "About".

Screen Shot 2020-09-10 at 4 55 07 PM

Screen Shot 2020-09-10 at 4 57 05 PM

**Comment by dherman** [comment]
@amilajack I have a feeling I changed too many things at once with this PR and may have overwhelmed you. While I feel the information architecture of the docs needs some work, I'll try to put it back closer to the way it was so this PR can be more focused just on the page layout and design.

**Comment by dherman** [comment]
Changed the section name to "Introduction", per your suggestion.

**Review by amilajack — APPROVED** [review]
LGTM!

**Pull request merged**
